import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nexus Digital",
  description: "Generated by create next app",
  keywords: [],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className="scroll-smooth overflow-x-hidden">
      <body
        className={`${spaceGrotesk.className} bg-[#ffffff] overflow-x-hidden flex flex-col gap-[20px]`}
      >
        {children}
      </body>
    </html>
  );
}
