import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './globals.css'

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], style: ['normal'], weight: ['300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Nexus Digital',
  description: 'Generated by create next app',
  keywords: [],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>{children}</body>
    </html>
  )
}
